#! /bin/bash
#PBS -l walltime=06:00:00
#PBS -l mem=50Gb
#PBS -l nodes=1:ppn=8
#PBS -e /mnt/research/ShadeLab/WorkingSpace/Jackson/
#PBS -o /mnt/research/ShadeLab/WorkingSpace/Jackson/
#PBS -N Matching_Pairs
#PBS -A bicep
#PBS -M jacksonwsorensen@gmail.com
#PBS -m abe
cd /mnt/research/ShadeLab/WorkingSpace/Jackson
./Cen13_R2_Matches.sh
grep "@HWI" Cen13_mgDNA_Pooled_CTTGTA_L002_R2_001.qc.matches.fastq | awk '{print $1}' > Cen13_Matched_Headers.txt
./Cen13_R1_Matches.sh
