#! /bin/bash
#PBS -l walltime=06:00:00
#PBS -l mem=100Gb
#PBS -l nodes=1:ppn=12
#PBS -e /mnt/research/ShadeLab/WorkingSpace/
#PBS -o /mnt/research/ShadeLab/WorkingSpace/
#PBS -N QualityFiltering
#PBS -A bicep
#PBS -M jacksonwsorensen@gmail.com
#PBS -m abe
module load fastx
cd /mnt/research/ShadeLab/WorkingSpace/Jackson
fastx_quality_stats -i Cen13_mgDNA_Pooled_CTTGTA_L002_R1_001.qc.fastq -o Cen13_R1_Quality.txt -N
fastx_quality_stats -i Cen13_mgDNA_Pooled_CTTGTA_L002_R2_001.qc.fastq -o Cen13_R2_Quality.txt -N
