#! /bin/bash
#PBS -l walltime=07:00:00:00
#PBS -l mem=1500Gb
#PBS -l nodes=1:ppn=16
#PBS -e /mnt/research/ShadeLab/WorkingSpace/Jackson
#PBS -o /mnt/research/ShadeLab/WorkingSpace/Jackson
#PBS -N Spades_Assembly_Direct
#PBS -A bicep
#PBS -M jacksonwsorensen@gmail.com
#PBS -m abe 
module load SPAdes/3.6.0
cd /mnt/research/ShadeLab/WorkingSpace/Jackson
spades.py -1 Cen13_mgDNA_Pooled_CTTGTA_L002_R1_001.qc.fastq -2 Cen13_mgDNA_Pooled_CTTGTA_L002_R2_001.qc.fastq -o SpadesAssembly -t $PBS_NUM_PPN -m 1500 --tmp-dir /mnt/scratch/sorens75/ -k 27,37,47,57,67,77,87,97,107
